### ISSUE TITLE
Is symfony 6 supported 

### ISSUE THREAD

**Issue by aszenz** [ForestAdmin/symfony-forestadmin#12]
## Expected behavior

Package should install on a project using a latest symfony version

## Actual behavior

Installation on a project using symfony 6 fails because composer couldn't resolve to installable set of packages

## Context

* Package Version:1.0.0-beta.9
* PHP Version:8.1

**Comment by nicolasalexandre9** [comment]
Hi @aszenz,

I'm able to reproduce this bug on my end as well. I'll open a ticket in our internal issue tracker.

I'll let you know when the issue is fixed.

Thanks for reporting this 🙏
